name: Run Ngrok Script

on: [push] # Atur trigger sesuai kebutuhan Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update and Upgrade
      run: |
        git
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Set Ngrok Auth Token
      run: |
        ./ngrok authtoken 2VIxGn1iB9vSlFSHFhfc7gGQUAV_566u6yhqcykzuETbRf4Fw

    - name: Give Execution Permissions
      run: |
        chmod +x ngrok.sh
        chmod +x runss.sh

    - name: Run Ngrok Script
      run: |
        ./ngrok.sh
