on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1
        with:
          message-title: New Commits Pushed
          webhook: https://discord.com/api/webhooks/1141729039673987185/mXKZ_FpRtn9r0gDKisYo-6GnL7Ogf2FC_pN65R7AzyQBQe-W3fkqthtPQDu1LycTRJpC
